from typing import Protocol, Self
from quantro.domain.models import State


class UnitOfWork(Protocol):
    state: State

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
